# Generated by Django 6.0.6 on 2026-06-15 10:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
